url: https://github.com/Mishal-Benz/undefined.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Team New Site
# email: your-email@domain.com
description: "Webpage for HAI and RAI Teams"


# Team names, titles and social links
people:
- name: Dr. Markus GÃ¶tz
  pic: mgoetz
  position: Team Lead
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: stack-overflow
  #    url: #

- name: Dr. Charlotte Debus
  pic: cdebus
  position: Team Lead
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: linkedin
  #    url: #

- name: Dr. Mishal Benz
  pic: mbenz
  position: Helmholtz AI Consultant
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #   url: #
  #  - title: google-plus
  #    url: #

- name: Dr. Marie Weiel
  pic: mweiel
  position: Helmholtz AI Consultant
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #   url: #
  #  - title: google-plus
  #    url: #
#


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Helmholtz-AI-Energy

# Postal address (add as many lines as necessary)
address:
  - line: Karlsruhe Institute of Technology, Campus North
  - line: Hermann-von-Helmholtz-Platz 1, 76344 Eggenstein-Leopoldshafen, Germany

# Build settings
markdown: kramdown
permalink: pretty